set -g prefix C-s

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind x kill-pane

bind-key C-t split-window -v -p 30

set -g @plugin 'christoomey/vim-tmux-navigator'

# Ativa a barra de status
set -g status on

# começar a numeração das janelas em 1
set -g base-index 1

# começar a numeração dos painéis em 1
setw -g pane-base-index 1

# reordenar abas automaticamente
set -g renumber-windows on

# Mantém sessão ativas do nvim com ressurect
set -g @resurrect-strategy-nvim 'session'

# Define a posição e altura da barra
set -g status-position bottom
set -g status-interval 5
set -g status-justify left
set -g status-left-length 30
set -g status-right-length 150
set -g status-bg colour235          # Fundo principal (cinza muito escuro)
set -g status-fg colour244

set -g @plugin 'tmux-plugins/tmux-resurrect'

# --- Lado Esquerdo da Barra (status-left) ---
set -g status-left-length 30
set -g status-left '#[fg=colour15,bg=colour26,bold] #S #[fg=colour26,bg=colour235,nobold]'

# --- Lista de Janelas (As "Abas") ---
# A MUDANÇA ESTÁ AQUI: Usamos colour33 (azul oceano escuro) para a aba ativa.
set -g window-status-current-format '#[fg=colour235,bg=colour33]#[fg=colour15,bg=colour33,noreverse,bold] #I  #W #[fg=colour33,bg=colour235]'

# Formato das Janelas INATIVAS
set -g window-status-format '#[fg=colour244,bg=colour235] #I  #W '
set -g window-status-separator ' '

# --- Lado Direito da Barra (status-right) ---
set -g status-right-length 50
#set -g status-right '#[fg=colour235,bg=colour26]#[fg=colour15,bg=colour26] %H:%M  %d/%m/%Y '# --- Outras Configurações Úteis ---
# Ativa o mouse
set -g mouse on

# Muda o prefixo padrão de Ctrl+b para Ctrl+a (mais fácil de alcançar)
# Descomente a linha abaixo se quiser usar
# unbind C-b
# set -g prefix C-a
# bind C-a send-prefix

# Ctrl+x cria nova janela (sem prefixo)
bind-key -n C-x new-window

# Ctrl+z fecha a janela atual (sem prefixo)
bind-key -n C-z kill-window

# Navegar entre janelas (abas) com Alt + 1..6 (sem prefixo)
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin "nordtheme/tmux"


unbind-key c
bind-key c command-prompt -p "Window name:" "new-window -n '%%'"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
